In [3]:
import numpy as np 

In [10]:
np.ones((3,5)) 


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.random.normal(10,4,(3,4)) #Normal dağılım 0olacak şekilde bir matrix oluşturduk

array([[13.29905137,  4.6590678 ,  7.99530826,  5.39112358],
       [ 7.87809313, 18.82024891,  5.74230133,  4.68434448],
       [ 9.74836912,  4.04898691, 10.4872304 ,  2.1499505 ]])

In [17]:
np.random.randint(0,10,(3,5))

array([[7, 3, 2, 7, 3],
       [2, 4, 7, 1, 0],
       [0, 4, 4, 2, 9]])

* ndim: Boyut Sayısı
* Shape:Boyut Bilgisi
* size:
* dtype: veri tipi

In [18]:
my_array=np.random.randint(10,size=10)

In [19]:
my_array.ndim

1

In [20]:
my_array.shape

(10,)

In [22]:
my_array=np.random.randint(0,10,(3,5))

In [25]:
my_array.ndim

2

In [26]:
my_array.shape

(3, 5)

In [29]:
x=np.arange(1,5)
y=np.arange(5,10)

In [30]:
np.concatenate([x,y]) #tek boyutta birleşitirme

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a=np.array([[1,2,3],[5,7,9]])

In [35]:
np.concatenate([a,a],axis=0)


array([[1, 2, 3],
       [5, 7, 9],
       [1, 2, 3],
       [5, 7, 9]])

In [37]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [5, 7, 9, 5, 7, 9]])

In [38]:
my_array=np.array([1,2,3,99,99,3,2,1])

In [40]:
a,b,c=np.split(my_array,[3,5]) #Diziyi belli bir düzende böldük

In [42]:
print(a,b,c)

[1 2 3] [99 99] [3 2 1]


In [43]:
m=np.arange(16).reshape(4,4)

In [45]:
a,b=np.vsplit(m,[2]) # satır bazında böldü 2D array'i

In [46]:
print(a,b)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [48]:
a,b=np.hsplit(m,[2]) # sutun bazında böldü 2D array'i

In [53]:
my_array=np.array([1,2,3,99,99,3,2,1,9,15,17,14])

In [52]:
np.sort(my_array) #Sıralama yapar

array([ 1,  1,  2,  2,  3,  3,  9, 14, 15, 17, 99, 99])

In [54]:
my_array.sort # bu fonksiyon diziyi değiştirir
my_array

array([ 1,  2,  3, 99, 99,  3,  2,  1,  9, 15, 17, 14])

In [55]:
my_array=np.random.normal(20,5,(3,3))

In [56]:
np.sort(my_array,axis=1)

array([[15.94517672, 16.08326265, 21.4218782 ],
       [16.66524738, 16.88284287, 20.83734201],
       [17.40224728, 21.5207938 , 22.11658011]])

In [57]:
5*np.array([1, 2,3])

array([ 5, 10, 15])