In [1]:
import numpy as np

In [2]:
behindProcess=np.random.randint(15,size=(5,5))

In [3]:
alt_a=behindProcess[0:3,0:4]

In [5]:
alt_a[0,0]=999 # alt kümede bir elemanı değiştirdik

In [6]:
alt_a

array([[999,  10,   8,   5],
       [  2,   9,   5,   3],
       [  9,   3,  14,   4]])

In [8]:
behindProcess # alt kümede değiştirdiğimiz eleman ana kümede de değişti

array([[999,  10,   8,   5,  14],
       [  2,   9,   5,   3,   9],
       [  9,   3,  14,   4,   9],
       [ 11,  14,   3,   7,   6],
       [  7,   3,  10,  13,   3]])

In [9]:
behindProcess2=np.random.randint(15,size=(5,5))

In [11]:
alt_b=behindProcess2[0:3,0:4].copy() # copy() methodu ile alt kğmeyi ana kümeden bağımsızlaştırdık

In [12]:
alt_b[0,0]=111

In [13]:
alt_b

array([[111,  12,   0,  13],
       [ 13,   5,  10,   5],
       [  9,   6,   8,   2]])

In [15]:
behindProcess2 # görüldüğü kimi alt küme bağımsız oldu

array([[ 2, 12,  0, 13,  3],
       [13,  5, 10,  5,  9],
       [ 9,  6,  8,  2, 12],
       [ 4, 12, 13,  7, 12],
       [ 9, 10, 13,  4, 11]])

 ``` Fancy Index ile ELemanlara Erişmek ```

In [16]:
v=np.arange(0,30,3)

In [18]:
get_=[1,3,5]


In [20]:
v[get_] # v dizesi içinden 1 ,3 ve 5 elemananları getirir

array([ 3,  9, 15])

In [22]:
m=np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
firstElemenet=np.array([0,1])
secondElement=np.array([1,2])
m[firstElemenet,secondElement] #fancy eleman seçimi ile eleman seçtik

array([1, 5])

Koşullu Eleman Islemleri

In [24]:
m>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [25]:
m % 2 ==0

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [26]:
m[m % 2 ==0] # dize içinde koşulu karşılayan değerleri getirir

array([0, 2, 4, 6, 8])

In [27]:
m**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [28]:
#Ufunc

In [29]:
newElement=np.array([1,2,3,4,5,6,7,8,9])

In [31]:
np.subtract(newElement,1) # her elemandan 1  çıkardık

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
np.add(newElement,1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.multiply(newElement,4)

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [34]:
?np

Type:        module
String form: <module 'numpy' from 'c:\\Users\\doguk\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\doguk\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

In [37]:
newElement.mean()
newElement.std()

2.581988897471611

In [43]:
x=np.array([[5,1],[1,3]])
y=np.array([12,10])

In [44]:
a=np.linalg.solve(x,y)

In [46]:
a # iki bilinmeyenli denklem çözümü

array([1.85714286, 2.71428571])