In [2]:
import numpy as np 

In [3]:
np.ones((3,5)) 


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [5]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [6]:
np.random.normal(10,4,(3,4)) #Normal dağılım 0olacak şekilde bir matrix oluşturduk

array([[11.39540715, 11.74154615,  6.26042795, 15.29277564],
       [ 7.86418023, 12.21996216,  8.49716699,  9.87755246],
       [12.78448524, 13.37703664, 11.01022062, 11.97230669]])

In [7]:
np.random.randint(0,10,(3,5))

array([[7, 1, 7, 8, 0],
       [3, 6, 9, 1, 7],
       [3, 4, 3, 1, 3]])

* ndim: Boyut Sayısı
* Shape:Boyut Bilgisi
* size:
* dtype: veri tipi

In [8]:
my_array=np.random.randint(10,size=10)

In [9]:
my_array.ndim

1

In [10]:
my_array.shape

(10,)

In [11]:
my_array=np.random.randint(0,10,(3,5))

In [12]:
my_array.ndim

2

In [13]:
my_array.shape

(3, 5)

In [14]:
x=np.arange(1,5)
y=np.arange(5,10)

In [15]:
np.concatenate([x,y]) #tek boyutta birleşitirme

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a=np.array([[1,2,3],[5,7,9]])

In [17]:
np.concatenate([a,a],axis=0)


array([[1, 2, 3],
       [5, 7, 9],
       [1, 2, 3],
       [5, 7, 9]])

In [18]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [5, 7, 9, 5, 7, 9]])

In [19]:
my_array=np.array([1,2,3,99,99,3,2,1])

In [20]:
a,b,c=np.split(my_array,[3,5]) #Diziyi belli bir düzende böldük

In [21]:
print(a,b,c)

[1 2 3] [99 99] [3 2 1]


In [22]:
m=np.arange(16).reshape(4,4)

In [23]:
a,b=np.vsplit(m,[2]) # satır bazında böldü 2D array'i

In [24]:
print(a,b)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [25]:
a,b=np.hsplit(m,[2]) # sutun bazında böldü 2D array'i

In [26]:
my_array=np.array([1,2,3,99,99,3,2,1,9,15,17,14])

In [27]:
np.sort(my_array) #Sıralama yapar

array([ 1,  1,  2,  2,  3,  3,  9, 14, 15, 17, 99, 99])

In [28]:
my_array.sort # bu fonksiyon diziyi değiştirir
my_array

array([ 1,  2,  3, 99, 99,  3,  2,  1,  9, 15, 17, 14])

In [29]:
my_array=np.random.normal(20,5,(3,3))

In [30]:
np.sort(my_array,axis=1)

array([[15.65281432, 18.26120761, 20.15833665],
       [15.28973273, 20.41691251, 23.55103625],
       [12.68360846, 21.87295943, 24.3997976 ]])

In [31]:
5*np.array([1, 2,3])

array([ 5, 10, 15])

In [32]:
20*np.array([1, 2,3])

array([20, 40, 60])

In [36]:
temp=np.random.randint(10,size=(5,5))
temp

array([[9, 3, 4, 4, 3],
       [3, 4, 9, 6, 6],
       [4, 6, 0, 2, 2],
       [8, 8, 2, 1, 5],
       [9, 5, 9, 8, 7]])

In [34]:
temp[:,0] # Birinci sutuna eriştik

array([6, 2, 1, 7, 5])

In [44]:
temp[:,3]


array([4, 6, 2, 1, 8])

In [40]:
temp[0,:] # satır seçme işlemi

array([9, 3, 4, 4, 3])

In [43]:
temp[0:2,0:3] # satır ve sutun birlikte seçimi

array([[9, 3, 4],
       [3, 4, 9]])

In [45]:
temp[0, [1,2]]

array([3, 4])